-- =====================================================================
-- LogiSync / OpsCenter — backend schema (reference)
-- Supabase project: hevabfnedijtajgcvlel
--
-- This file documents the database objects the app relies on. It is the
-- cumulative result of the migrations applied via Supabase. Writes never
-- happen directly against tables from the browser — they go through
-- PIN-verified SECURITY DEFINER functions; RLS keeps tables read-only to
-- the anon (publishable) key. See SECURITY_NOTES.md.
-- =====================================================================

-- ---------- core tables (pre-existing) ----------
-- public.tasks, public.weekly_numbers, public.coaching_records,
-- public.recurring_tasks, public.users  (managed elsewhere)

-- ---------- users: identity + hierarchy ----------
-- alter table public.users add column email text;          -- Gmail (ready for Google sign-in)
-- alter table public.users add column access_level text default 'agent'; -- leader | manager | agent
-- create unique index users_email_unique on public.users (lower(email)) where email is not null;

-- ---------- departments ----------
create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz default now()
);
alter table public.departments enable row level security;
create policy dept_public_read on public.departments for select to anon, authenticated using (true);

-- ---------- aux tracker ----------
create table if not exists public.aux_logs (
  id bigint generated by default as identity primary key,
  agent text not null,
  aux_type text not null,            -- Restroom | Break | Away Phone call | Away Order | Prayer
  start_time timestamptz not null default now(),
  end_time timestamptz,
  duration_seconds integer,
  note text,
  logged_by text,
  created_at timestamptz default now()
);
alter table public.aux_logs enable row level security;
create policy aux_public_read on public.aux_logs for select to anon, authenticated using (true);
-- writes only via secure_start_aux / secure_stop_aux / secure_delete_aux

create table if not exists public.department_aux_limits (
  id bigint generated by default as identity primary key,
  department text not null,
  aux_type text not null,
  daily_limit_minutes integer not null default 0,   -- 0 = no limit; track & report only
  updated_at timestamptz default now(),
  unique (department, aux_type)
);
alter table public.department_aux_limits enable row level security;
create policy aux_limits_public_read on public.department_aux_limits for select to anon, authenticated using (true);

-- =====================================================================
-- Functions (SECURITY DEFINER, PIN-verified). See live DB for full bodies.
-- =====================================================================
-- public._auth_user(p_pin)            -> users      : verifies PIN, raises on miss
-- public._auth_leader(p_pin)          -> users      : as above + requires is_leader
-- public.verify_login(user, pin)      -> row         : login; returns name, dept, role,
--                                                       is_leader, email, access_level
-- public.visible_members(p_pin)       -> rows        : roster a user may see
--                                                       (leader=all, manager=own dept, agent=self)
--
-- Writes (PIN-gated):
--   secure_add_task / secure_update_task / secure_append_briefing / secure_archive_done
--   secure_save_weekly / secure_save_coaching / secure_delete_coaching / secure_park_stale
--   secure_start_aux(pin, agent, type) / secure_stop_aux(pin, id) / secure_delete_aux(pin, id)
--
-- Admin (leader-gated):
--   admin_list_users(pin)
--   admin_save_user(pin, id, name, email, dept, role, access_level, is_leader, new_pin)
--   admin_delete_user(pin, id)
--   admin_save_department(pin, id, name) / admin_delete_department(pin, id)
--   admin_set_aux_limit(pin, dept, aux_type, minutes)
-- =====================================================================
